config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  get 'signup', to: 'users#new'
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  
  resources :users
  resources :microposts
  post 'retweet', to: 'microposts#retweet'
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users do 
    member do
      get 'followings', 'followers', 'favorites', 'retweets'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    
    has_many :microposts
    
    has_many :following_relationships, class_name: "Relationship",
                                       foreign_key: "follower_id",
                                       dependent: :destroy
                                       
    has_many :following_users, through: :following_relationships, source: :followed
    
    has_many :follower_relationships, class_name: "Relationship",
                                      foreign_key: "followed_id",
                                      dependent: :destroy
    
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    has_many :favorites, dependent: :destroy
    
    has_many :favorite_microposts, through: :favorites, source: :micropost

    # 他のユーザーをフォローする
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    # フォローしているユーザーをアンフォローする
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    # あるユーザーをフォローしているかどうか？
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
    
    def favorite(micropost)
        #Favorite.create(micropost_id: micropost.id, user_id: self.id)
        favorites.find_or_create_by(micropost_id: micropost.id)
    end
        
    def unfavorite(micropost)
        favorite = favorites.find_by(micropost_id: micropost.id)
        favorites.destroy if favorite
    end
    
    def favorite?(micropost)
        favorite_microposts.include?(micropost)
    end
    
    def retweet_to?(micropost)
        microposts.exists?(original_id: micropost.id)
    end
    
    
    
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    validates :location, length: { maximum: 100 }
    validates :bio, length: { maximum: 300 }
    
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :followers, :followings, :favorites]
  before_action :user_match, only: [:edit, :update]
  before_action :logged_in_user, only: [:index, :followings, :followers, :favorites]
  
  def index
    @users = User.all
  end
  
  def show
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to current_user , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def followings
    @users = @user.following_users
  end
  
  def followers
    @users = @user.follower_users
  end
  
  def favorites
   @microposts = @user.favorite_microposts
  end
  
  def retweet_to?(micropost)
    microposts.exists?(original_id: micropost.id)
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :location, :bio)
  end
  
  def user_match
    if current_user.id != params[:id].to_i
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= f.submit "Favo", class: "favorite_form btn btn-primary" %>
  <button class="btn btn-default"><i class="fa fa-heart-o"></i></button>
<% end %>

app/views/users/_favorite_form.html.erb
<% if current_user != @user %>
  <div id="favorite_form_<%= micropost.id %>">
  <% if current_user.favorite?(micropost) %>
    <%= render 'users/unfavorite', micropost: micropost %>
  <% else %>
    <%= render 'users/favorite', micropost: micropost %>
  <% end %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_retweet.html.erb
<%= form_for(current_user.microposts.build, url: retweet_path) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= f.submit "Re", class: "retweet_form btn btn-success" %>
  <button class="btn btn-default"><i class="fa fa-retweet" aria-hidden="true"></i></button>
<% end %>

app/views/users/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(micropost_id: micropost.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfavo", class: "unfavorite_form btn btn-default" %>
  <button class="btn btn-primary"><i class="fa fa-heart-o"></i></button>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li class="panel-body">
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<div class="row">
    <%= form_for(current_user, html: {class: 'form-horizontal' }) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
    
        <div class="form-group">
            <%= f.label :name, "Name", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.text_field :name, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :email, "Email", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.email_field :email, class: "form-control" %>
            </div>
        </div>
        
         <div class="form-group">
            <%= f.label :password, "Password", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.password_field :password, class: "form-control" %>
            </div>
        </div>
        
         <div class="form-group">
            <%= f.label :password_confirmation, "Confirmation", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :location, "Location", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.text_field :location, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :bio, "Bio", class: "control-label col-md-2" %>
            <div class="col-md-10">
                <%= f.text_area :bio, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.submit "Update my profile!", class: "btn btn-large btn-primary col-md-6 col-md-offset-3" %>
        </div>
    
    <% end %>
</div>

app/views/users/followers.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1 id="myname">
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
       <section id="user_location_bio">
      <p>location : <%= @user.location %></p>
      <p>bio : <%= @user.bio %></p>
    </section>
    </aside>
    <div class="col-md-8">
      <section  class="followings_followers">
          <h2 class="panel-heading">Followers</h2>
            <ul>
              <%= render @users %>
            </ul>
      </section>
    </div>
</div>

app/views/users/followings.html.erb
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1 id="myname">
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
    <div class="col-md-8">
      <section  class="followings_followers">
          <h2 class="panel-heading">Followings</h2>
            <ul>
              <%= render @users %>
            </ul>
      </section>
    </div>
</div>

app/views/users/index.html.erb
<h2 id="userindex">All Users</h2>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sigh up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <div class="form-group">
                <%= f.label :name, class: "control-label" %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :email, class: "control-label" %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :password, class: "control-label" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 id="myname">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section id="user_location_bio">
      <p>location : <%= @user.location %></p>
      <p>bio : <%= @user.bio %></p>
      <p>Favo: <%= link_to "My Favorites", favorites_user_path(@user) %></p>
    </section>
    <section>
      <ul class="followbtn">
         <li class="btn btn-primary"><%= link_to "Followings", followings_user_path(@user)  %></li>
         <li class="btn btn-primary"><%= link_to "Followers", followers_user_path(@user) %></li>
       </ul>
    </section>
  </aside>
  
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3 id="personal-micropost">Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>